suppressPackageStartupMessages(source('validate_v6_public.R'))
reject<-function(x)inherits(tryCatch(force(x),error=identity),'error')
p<-data.frame(game_id=as.character(1:6),season=rep(c(2019,2021,2022),each=2),cutoff=rep(c('2019-09-02','2021-09-06','2022-09-05'),each=2),pred_margin=c(4,-4,0,2,1,-2),actual_margin=c(7,-1,0,3,-2,2))
l<-data.frame(game_id=p$game_id,spread=c(-3,3,0,-2,-1,1),spread_semantics='home_team_spread',closing_verified=FALSE)
r<-v6_market_report(p,l);stopifnot(r$metrics$n==6,r$metrics$model_line_ties==3,r$metrics$pushes==1,!r$metrics$all_closing_verified)
stopifnot(reject(v6_market_report(p,l[-1,])),reject(v6_market_report(p,rbind(l,l[1,]))))
q<-l;q$spread_semantics<-'unverified';stopifnot(reject(v6_market_report(p,q)));q<-l;q$spread[1]<-NA;stopifnot(reject(v6_market_report(p,q)));q<-p;q$market_rating<-1;stopifnot(reject(v6_market_report(q,l)))
v6_write(data.frame(test=c('ATS coverage','ATS duplicate','ATS semantics','ATS missing line','market ingress','ties pushes and unverified closing retained'),pass=TRUE),'reporting_tests')
cat('6 market reporting tests passed\n')
